services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-speech_to_info}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_lite_data:/var/lib/postgresql/data

volumes:
  postgres_lite_data:
